spring:
  application:
    name: ${STOCK_APPLICATION_NAME}
  
  datasource:
    driver-class-name: ${STOCK_DATASOURCE_DRIVER}
  
  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${STOCK_GOOGLE_CLIENT_ID}
            client-secret: ${STOCK_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${STOCK_GOOGLE_REDIRECT_URI}
          kakao:
            client-id: ${STOCK_KAKAO_CLIENT_ID}
            client-secret: ${STOCK_KAKAO_CLIENT_SECRET}
            redirect-uri: ${STOCK_KAKAO_REDIRECT_URI}
          naver:
            client-id: ${STOCK_NAVER_CLIENT_ID}
            client-secret: ${STOCK_NAVER_CLIENT_SECRET}
            redirect-uri: ${STOCK_NAVER_REDIRECT_URI}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

openapi:
  api-key: ${STOCK_OPENAPI_KEY}
  stock-price-info-url: ${STOCK_OPENAPI_STOCK_PRICE_URL}
korea-investment-api:
  api-key: ${STOCK_KIS_API_KEY}
  secret-key: ${STOCK_KIS_SECRET_KEY}
  dev-api-url: ${STOCK_KIS_DEV_API_URL}
  oauth2-token-url: ${STOCK_KIS_OAUTH2_TOKEN_URL} # 토큰P
  inquire-price-url: ${STOCK_KIS_INQUIRE_PRICE_URL} # 주식시세
  volume-rank-url: /uapi/domestic-stock/v1/quotations/volume-rank
  fluctuation-url: /uapi/domestic-stock/v1/ranking/fluctuation
  market-cap-url: /uapi/domestic-stock/v1/ranking/market-cap
jwt:
  secret: ${STOCK_JWT_SECRET}
  expiration: ${STOCK_JWT_EXPIRATION}
  refreshExpiration: ${STOCK_JWT_REFRESH_EXPIRATION}
