spring:
  config:
    activate:
      on-profile: local
  profiles:
    url: http://localhost/
  
  datasource:
    url: ${STOCK_DATASOURCE_LOCAL_URL}
    username: ${STOCK_DATASOURCE_LOCAL_USERNAME}
    password: ${STOCK_DATASOURCE_LOCAL_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: ${STOCK_JPA_OPTION_ISSHOW}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${STOCK_GOOGLE_LOCAL_CLIENT_ID}
            client-secret: ${STOCK_GOOGLE_LOCAL_CLIENT_SECRET}
            redirect-uri: ${STOCK_GOOGLE_LOCAL_REDIRECT_URI}
          kakao:
            client-id: ${STOCK_KAKAO_LOCAL_CLIENT_ID}
            client-secret: ${STOCK_KAKAO_LOCAL_CLIENT_SECRET}
            redirect-uri: ${STOCK_KAKAO_LOCAL_REDIRECT_URI}
          naver:
            client-id: ${STOCK_NAVER_LOCAL_CLIENT_ID}
            client-secret: ${STOCK_NAVER_LOCAL_CLIENT_SECRET}
            redirect-uri: ${STOCK_NAVER_LOCAL_REDIRECT_URI}
springdoc:
  default-consumes-media-type: ${STOCK_CONSUMES_MEDIATYPE}
  default-produces-media-type: ${STOCK_PRODUCES_MEDIATYPE}
  paths-to-match: ${STOCK_PATH_MATCH}
  swagger-ui:
    path: ${STOCK_SWAGGER_PATH}
    display-request-duration: ${STOCK_SWAGGER_DUTATION}
    groups-order: ${STOCK_SWAGGER_ORDER}
    operations-sorter: ${STOCK_SWAGGER_ISSORTER}
    disable-swagger-default-url: ${STOCK_SWAGGER_DISABLE}
    urls:
      - url: ${STOCK_SWAGGER_LOCAL_URL}
        name: ${STOCK_SWAGGER_NAME}
  api-docs:
    groups:
      enabled: ${STOCK_SWAGGER_ISGROUPS}
server:
  port: 80
