spring:
  config:
    activate:
      on-profile: dev
  profiles:
    url: ${STOCK_PROFILES_DEV_URL}

  datasource:
    url: ${STOCK_DATASOURCE_DEV_URL}
    username: ${STOCK_DATASOURCE_DEV_USERNAME}
    password: ${STOCK_DATASOURCE_DEV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: ${STOCK_JPA_OPTION_ISSHOW}

springdoc:
  default-consumes-media-type: ${STOCK_CONSUMES_MEDIATYPE}
  default-produces-media-type: ${STOCK_PRODUCES_MEDIATYPE}
  paths-to-match: ${STOCK_PATH_MATCH}
  swagger-ui:
    path: ${STOCK_SWAGGER_PATH}
    display-request-duration: ${STOCK_SWAGGER_DUTATION}
    groups-order: ${STOCK_SWAGGER_ORDER}
    operations-sorter: ${STOCK_SWAGGER_ISSORTER}
    disable-swagger-default-url: ${STOCK_SWAGGER_DISABLE}
    urls:
      - url: ${STOCK_SWAGGER_DEV_URL}
        name: ${STOCK_SWAGGER_NAME}
  api-docs:
    groups:
      enabled: ${STOCK_SWAGGER_ISGROUPS}
