spring:
  application:
    name: ${STOCK_APPLICATION_NAME}

  datasource:
    driver-class-name: ${STOCK_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${STOCK_GOOGLE_CLIENT_ID}
            client-secret: ${STOCK_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${STOCK_GOOGLE_REDIRECT_URI}
          kakao:
            client-id: ${STOCK_KAKAO_CLIENT_ID}
            client-secret: ${STOCK_KAKAO_CLIENT_SECRET}
            redirect-uri: ${STOCK_KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao
          naver:
            client-id: ${STOCK_NAVER_CLIENT_ID}
            client-secret: ${STOCK_NAVER_CLIENT_SECRET}
            redirect-uri: ${STOCK_NAVER_REDIRECT_URI}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

springdoc:
  default-consumes-media-type: ${STOCK_CONSUMES_MEDIATYPE}
  default-produces-media-type: ${STOCK_PRODUCES_MEDIATYPE}
  paths-to-match: ${STOCK_PATH_MATCH}
  swagger-ui:
    path: ${STOCK_SWAGGER_PATH}
    display-request-duration: ${STOCK_SWAGGER_DUTATION}
    groups-order: ${STOCK_SWAGGER_ORDER}
    operations-sorter: ${STOCK_SWAGGER_ISSORTER}
    disable-swagger-default-url: ${STOCK_SWAGGER_DISABLE}
  api-docs:
    groups:
      enabled: ${STOCK_SWAGGER_ISGROUPS}

openapi:
  api-key: ${STOCK_OPENAPI_KEY}
  stock-price-info-url: ${STOCK_OPENAPI_STOCK_PRICE_URL}

jwt:
  secret: ${STOCK_JWT_SECRET}
  expiration: ${STOCK_JWT_EXPIRATION}
  refreshExpiration: ${STOCK_JWT_REFRESH_EXPIRATION}

logging:
  level:
    org.springframework.web: DEBUG  # 웹 관련 디버깅 로그
    org.springframework.security: DEBUG  # 보안 관련 디버깅 로그
    org.springframework.boot: DEBUG  # Spring Boot 기본 디버깅 로그
    com.profitkey: DEBUG  # 자체 패키지 관련 디버깅 로그
